CREATE EXTENSION IF NOT EXISTS pgcrpyto;

/* DEFINICOES */

CREATE TABLE IF NOT EXISTS users(
    userID SERIAL PRIMARY KEY,
    username VARCHAR(50),
    pass VARCHAR(128)
);

CREATE TABLE IF NOT EXISTS posts(
    postID SERIAL PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    body VARCHAR(1000),
    creator INT NOT NULL REFERENCES users(userID)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS responses(
    responseID SERIAL PRIMARY KEY,
    body VARCHAR(1000) NOT NULL,
    postID INT NOT NULL REFERENCES posts(postID)
    ON DELETE CASCADE ON UPDATE CASCADE,
    creatorID INT NOT NULL REFERENCES users(userID)
    ON DELETE CASCADE ON UPDATE CASCADE
);

/* TRIGGERS */

CREATE OR REPLACE FUNCTION password_insert() RETURNS TRIGGER AS $$
BEGIN
    NEW.pass = crypt(NEW.pass, gen_salt('sha256crypt', 100));

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER password_insert
BEFORE INSERT ON users
FOR EACH ROW EXECUTE FUNCTION password_insert();
